config/routes.rb
Survey::Application.routes.draw do

  get "questions/show"

  get "questions/create"

  get "questions/new"

  get "questions/update"

  get "questions/edit"

  get "questions/destroy"

  get "answers/show"

  get "answers/create"

  get "answers/new"

  get "answers/update"

  get "answers/edit"

  get "answers/destroy"

  match "polls/:id" => "polls#destroy", :via => :delete, :as => :delete_poll

  match '/polls/toggle_live/:poll_id' => 'polls#toggle_live', :via => :put, :as => 'polls_toggle_live'
  

  devise_for :users
  
  devise_scope :users do
    resources :polls, :except => [:destroy] do
      resources :questions, :except => [:index] do
        resources :answer, :except => [:index]
      end
    end
  end

  get "registrations/after_sign_up_path_for"

  post '/sms' => 'sms#create'

  get "home/index"

  
  

  

  authenticated do
    root :to => 'home#dashboard'
  end

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    render :layout => 'homepage'
  end

  def dashboard
    render :layout => 'application'
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/_dashboard.html.haml
<h1> Test</h1>

app/views/home/dashboard.html.haml
.dashboard-wrapper.row.span12 

  .user-polls.span8
    %h2 Your Polls
    %table.table.striped
      - if current_user.polls
        - current_user.polls.each do |poll| 
          %tr.polls-data
            %td.poll-show
              / Need to add (poll) as it needs the ID to match to the route.
              =link_to "#{poll.title} #{poll.id}", poll_path(poll)
            %td
              =link_to "Edit", edit_poll_path(poll)
            %td[poll]
              - if poll.is_live
                = link_to "Stop", polls_toggle_live_path(poll.id), :method => :put, :remote => true, :class=> 'btn btn-danger btn-small stop-poll', :id => poll.id
              -else
                = link_to "Start", polls_toggle_live_path(poll.id), :method => :put, :remote => true, :class=> 'btn btn-success btn-small start-poll', :id => poll.id
              %td
                = link_to "Delete", delete_poll_path(poll.id),:remote => true, :id => poll.id, :method => :delete, :class => 'btn btn-danger btn-small delete-poll'


  .create-polls.span4
    = link_to "Create Poll", new_poll_path, :class => 'btn btn-success btn-large'


    

app/views/home/index.html.haml
.page-titles
  %h1.app-name ROGO
  %h4.tagline Ask the Audience

.navcontainer
  %div#middle
    %ul#nav
      %li
        = link_to 'About', '#'
      %li#signup
        = link_to 'Sign Up', '#', :id => "signup"
        = render 'devise/registrations/new'
      %li#login
        = link_to 'Login', '#', :id =>'login'
        = render 'devise/sessions/new'